task:
  - init : |
        sudo apt update
        sudo apt install -y mysql=server
        sudo service mysql start
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '#skcc06433'; FLUSH PRIVILEGES;"
    command: echo "MySQL setup complete!"