image:
  file: .gitpod.Dockerfile

tasks:
  - name: MySQL docker # docker-compose up -d
    command: | 
      docker compose up -d
      docker ps
    openMode: tab-after

ports:
  - port: 3306
    visibility: public
    onOpen: ignore